name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Pack Logic
      run: dotnet pack
    - name: Nuget Push
      run: dotnet nuget push *.nupkg
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish AnimalAdoption.Web.Portal -o AnimalAdoption.Web.Portal/published
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: published_portal
        path: ${{ github.workspace }}/AnimalAdoption.Web.Portal/published
